### ISSUE TITLE
This error will be reported after training.TypeError: evaluate() missing 1 required positional argument: 'eval_dataset'

### ISSUE THREAD

**Issue by lihuiuyun** [awsm-research/LineVul#5]
Traceback (most recent call last):
  File "/opt/data/private/lhy/LineVul-main/LineVul-main/linevul/linevul_main.py", line 1311, in <module>
    main()
  File "/opt/data/private/lhy/LineVul-main/LineVul-main/linevul/linevul_main.py", line 1298, in main
    result = evaluate(args, model, tokenizer)
TypeError: evaluate() missing 1 required positional argument: 'eval_dataset'

**Comment by MichaelFu1998-create** [comment]
Hi @lihuiuyun
please use do_train and do_test and avoid using do_eval
the evaluation will be done during training
by default, we evaluate once per epoch
if you wish to customize this, you may modify this line https://github.com/awsm-research/LineVul/blob/3cfbfaaf380aed30224100f091826da8e087df37/linevul/linevul_main.py#L122
